/******************************************************************************
* Authors:    Michael Myer, David Olah                                        *
* Emails:     mmyer488@mtroyal.ca, dolah663@mtroyal.ca                        *
* Course:     COMP 2659                                                       *
* Instructor: Paul Pospisil                                                   *
* File Name:  screen.h                                                        *
******************************************************************************/

#ifndef SCREEN_H
#define SCREEN_H

#include "types.h"

extern const UINT32 gameScreen[];

#endif
