/*******************************************************
* Authors:    Michael Myer, David Olah
* Emails:     mmyer488@mtroyal.ca, dolah663@mtroyal.ca
* Course:     COMP 2659
* Instructor: Paul Pospisil
* File Name:  Types.h
*******************************************************/

#ifndef TYPES_H
#define TYPES_H

typedef unsigned char UINT8;
typedef unsigned int  UINT16;
typedef unsigned long UINT32;

typedef int bool;
#define true 1
#define false 0

#endif
